### ISSUE TITLE
Resources not being read

### ISSUE THREAD

**Issue by minikN** [JBlackN/dwm-xrdb#2] opened 2019-06-10 12:53 UTC
Hello, I'm trying to apply your patch for the version `6.2`. However, I'm having some troubles.

I adjusted your original patch to the following: [link](https://0x0.st/zutd.diff)
The config I use: [link](https://0x0.st/zut5.h)
Output of `xrdb -query`: [link](https://0x0.st/zuth.txt)

The way I understood it is, it doesn't matter what hex values I declare my colors in `config.h` because it will get overwritten from the `Xresources` value, therefore I declared `#000000` for every color.

But now my dwm is all black - I assume the colors from `xrdb` do not get read.

**Update:** The only thing I can think of is that in my `.Xresources` file, I do not declare the colors directly, rather I include them in another file:

`.Xresources`: [link](https://0x0.st/zuvz.c)
`.config/X/dwm.Xresources`: [link](https://0x0.st/zuvi.c)

**Update 2**: Okay I figured it out. One has to declare the colors directly in `.Xresources` and one must not use a predefined variables such as
```
#define base00 #000000
dwn.color00: base00
```
Is there any way around this? 

Thanks.

**Comment by mihirlad55** [comment] 2019-06-27 04:47
Hello,

I can confirm I am having the exact same problem. Definitions aren't working with dwm, however hardcoding the colors work as @minikN stated.

For example,
```
#define color1 #FF0000
dwm.normbgcolor: color1
```
does not work. However,
```
dwm.normbgcolor: #FF0000
```
does work.

`xrdb -query` shows that #FF0000 is being tied to dwm.normbgcolor for both of the above cases. Upon further experimentation, I did notice that having a space after the hex color does cause the given color to not be updated in dwm, similar to when using definitions. For example, `dwm.normbgcolor: #FF0000 ` doesn't work, but `dwm.normbgcolor: #FF0000` does.

Here's my fork of dwm and the commit with your applied patch: https://github.com/mihirlad55/dwm/commit/2fc09a5bed22aa6bcf018e878e2beaf6b6aeaf29.
Note: my next commit does update the .Xresources path in the config.

I've tested this with the most minimal .Xresources file such as the example shown above with literally nothing else and have had the same issue.

Thanks,
Mihir

**Comment by minikN** [comment] 2019-06-27 19:01
I've actually looked into the patch. The reason it works the way it does is because it's designed that way. All it does is to read the file you provide in your config file (it could be any file).

It then parses the file for the following:

```
dwm.normbordercolor
dwm.normbgcolor
dwm.normfgcolor
dwm.selbordercolor
dwm.selbgcolor
dwm.selfgcolor
```

And applies the colors. Nothing more, nothing less. It's not `xrdb` specific at all. So it doesn't work like the `xresources` patch for `st` for example. If you think about it, if it did, why would you have to provide the path for your config file?

I've actually tried porting the st patch to dwm. Not succeeded yet.

**Comment by mihirlad55** [comment] 2019-06-27 20:33
Oh that makes a lot of sense. I haven't actually looked into the source code for the patch since it applied cleanly. I didn't even think about why we required the path to .Xresources.

I don't want to come off the wrong way, but it sounds kind of misleading calling this an xrdb patch if it only parses the .Xresources file. Either way, I still appreciate this patch being out, since its still better than no patch.

@minikN Are you actively working on porting the patch from st? I am very new to linux and the X11 system, but if I get some time, I may give it a shot. It could also be a great way for me to learn dwm and X11 API.

@JBlackN Are you planning to implement full xrdb support in the near future?

**Comment by minikN** [comment] 2019-06-27 20:45
@mihirlad55 I'm still working on it. It compiles successfully but it doesn't work yet. Unfortunately, I don't have the time at the moment, but in a couple of weeks I will give it another shot. I'll keep you updated.

**Comment by JBlackN** [comment] 2019-07-08 20:05
Hello,

I wrote the patch this way, simply because it was more than sufficient for my use case at the time 😃 Unfortunately, I don't have much free time as my job keeps me very busy.

Anyway, I looked into it this morning and prepared new version of the patch (for dwm-6.2) inspired by the way st handles Xresources. My brief testing was successful:

~/.Xresources:

```c
#define S_base03 #002b36

dwm.normbgcolor: S_base03
dwm.normfgcolor: #839496
dwm.normbordercolor: #839496
dwm.selbgcolor: #073642
dwm.selfgcolor: #839496
dwm.selbordercolor: #b58900
```

~/.xinitrc:

```bash
xrdb ~/.Xresources
exec dwm
```

Scenario:

```bash
startx
# open terminal
vim .Xresources
# change S_base03
# save file
xrdb .Xresources
# Mod+F5
# color should reload
```

You can test for yourself and see whether the new version solves (or at least helps with) your issues. In any case, I'm glad you find the patch useful.

**Comment by mihirlad55** [comment] 2019-07-09 00:21
Hello,

I just tested the patch and can confirm it works perfectly. Thank you for updating the patch with xrdb.

**Comment by JBlackN** [comment] 2019-07-18 15:56
Hello,

I'm closing the issue for now, I'll reopen if needed.

**Closed as completed by JBlackN** 2019-07-18 15:56 UTC

**Comment by Ingvix** [comment] 2020-01-07 18:51
I'm having troubles getting the patch to work. Not sure what can I be doing wrong. At first I applied it on my build with many other patches and thought the other ones might be causing it to not work but even with a build with only this patch it won't change the colors. Everything else is default dmw-6.2. The colors stay default no matter what, reload, restart or reboot. My `xrdb -query`:
```
dwm.normbordercolor:    #585754;
dwm.normbgcolor:    #21201b;
dwm.normfgcolor:    #c7c7c6;
dwm.selbordercolor: #c7c7c6;
dwm.selbgcolor: #a8a7a1;
dwm.selfgcolor: #c7c7c6;
```

**Comment by Ingvix** [comment] 2020-01-07 22:25
Alright, false alarm. There's not suppose to be ';' at the end of the line in .Xresources... Don't know how I didn't realize sooner. Thanks for the great patch anyway.

**Comment by Simbaclaws** [comment] 2020-07-26 19:49
I created a .Xresources file with the following:
```
dwm.normbgcolor: #222222
dwm.normfgcolor: #bbbbbb
dwm.normbordercolor: #444444
dwm.selbordercolor: #00FF00
dwm.selbgcolor: #00FF00
dwm.selfgcolor: #3D3D3D
```

However when I recompile my dwm with only the xrdb patch in it just to test I'm getting the following errors:

```
>>> Compiling source in /var/tmp/portage/x11-wm/dwm-6.2/work/dwm-6.2 ...
make -j12 CC=x86_64-pc-linux-gnu-gcc dwm
x86_64-pc-linux-gnu-gcc -c -march=native -O2 -pipe -std=c99 -pedantic -Wall -Wno-deprecated-declarations -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA drw.c
x86_64-pc-linux-gnu-gcc -c -march=native -O2 -pipe -std=c99 -pedantic -Wall -Wno-deprecated-declarations -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA dwm.c
x86_64-pc-linux-gnu-gcc -c -march=native -O2 -pipe -std=c99 -pedantic -Wall -Wno-deprecated-declarations -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA util.c
dwm.c: In function ‘setup’:
dwm.c:1588:41: warning: passing argument 2 of ‘drw_scm_create’ from incompatible pointer type [-Wincompatible-pointer-types]
 1588 |   scheme[i] = drw_scm_create(drw, colors[i], 3);
      |                                   ~~~~~~^~~
      |                                         |
      |                                         const char **
In file included from dwm.c:45:
drw.h:42:6: note: expected ‘char **’ but argument is of type ‘const char **’
   42 | Clr *drw_scm_create(Drw *drw, char *clrnames[], size_t clrcount);
      |      ^~~~~~~~~~~~~~
dwm.c: In function ‘load_xresources’:
dwm.c:2192:11: error: ‘resources’ undeclared (first use in this function); did you mean ‘resource_load’?
 2192 |  for (p = resources; p < resources + LENGTH(resources); p++)
      |           ^~~~~~~~~
      |           resource_load
dwm.c:2192:11: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:18: dwm.o] Error 1
make: *** Waiting for unfinished jobs....
drw.c: In function ‘drw_text’:
drw.c:328:7: warning: ‘ew’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  328 |     w -= ew;
      |     ~~^~~~~
 * ERROR: x11-wm/dwm-6.2::gentoo failed (compile phase):
 *   emake failed
 *
```

Notice it saying: resources undeclared.
and also: expecting char ** but got const char **
I'm pretty sure it's unable to fetch the right colors for some reason. How would I fix this?

Could it be that I've done something wrong in my config?
```
/* See LICENSE file for copyright and license details. */

/* appearance */
static const char normbordercolor[] = "#444444";
static const char normbgcolor[]     = "#222222";
static const char normfgcolor[]     = "#BBBBBB";
static const char selbordercolor[]  = "#00FF00";
static const char selbgcolor[]      = "#00FF00";
static const char selfgcolor[]      = "#3D3D3D";
static const unsigned int borderpx  = 2;        /* border pixel of windows */
static const unsigned int snap      = 32;       /* snap pixel */
static const int showbar            = 1;        /* 0 means no bar */
static const int topbar             = 1;        /* 0 means bottom bar */
static const char *fonts[]          = { "monospace:size=10" };
static const char dmenufont[]       = "monospace:size=10";


/* tagging */
static const char *tags[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9" };

static const Rule rules[] = {
	/* xprop(1):
	 *	WM_CLASS(STRING) = instance, class
	 *	WM_NAME(STRING) = title
	 */
	/* class      instance    title       tags mask     isfloating   monitor */
	{ "Gimp",     NULL,       NULL,       0,            1,           -1 },
	{ "Firefox",  NULL,       NULL,       1 << 8,       0,           -1 },
	{ "Tilda",    NULL,       NULL,       0,            1,           -1 },
};

/* layout(s) */
static const float mfact     = 0.55; /* factor of master area size [0.05..0.95] */
static const int nmaster     = 1;    /* number of clients in master area */
static const int resizehints = 1;    /* 1 means respect size hints in tiled resizals */

static const Layout layouts[] = {
	/* symbol     arrange function */
	{ "[]=",      tile },    /* first entry is default */
	{ "><>",      NULL },    /* no layout function means floating behavior */
	{ "[M]",      monocle },
};

/* key definitions */
#define MODKEY Mod1Mask
#define TAGKEYS(KEY,TAG) \
	{ MODKEY,                       KEY,      view,           {.ui = 1 << TAG} }, \
	{ MODKEY|ControlMask,           KEY,      toggleview,     {.ui = 1 << TAG} }, \
	{ MODKEY|ShiftMask,             KEY,      tag,            {.ui = 1 << TAG} }, \
	{ MODKEY|ControlMask|ShiftMask, KEY,      toggletag,      {.ui = 1 << TAG} },

/* helper for spawning shell commands in the pre dwm-5.0 fashion */
#define SHCMD(cmd) { .v = (const char*[]){ "/bin/sh", "-c", cmd, NULL } }

/* commands */
static char dmenumon[2] = "0"; /* component of dmenucmd, manipulated in spawn() */
static const char *dmenucmd[] = { "dmenu_run", "-m", dmenumon, "-fn", dmenufont, "-nb", col_gray1, "-nf", col_gray3, "-sb", col_cyan, "-sf", col_gray4, NULL };
static const char *termcmd[]  = { "st", NULL };

static Key keys[] = {
	/* modifier                     key        function        argument */
	{ MODKEY,                       XK_p,      spawn,          {.v = dmenucmd } },
	{ MODKEY|ShiftMask,             XK_Return, spawn,          {.v = termcmd } },
	{ MODKEY,                       XK_b,      togglebar,      {0} },
	{ MODKEY,                       XK_j,      focusstack,     {.i = +1 } },
	{ MODKEY,                       XK_k,      focusstack,     {.i = -1 } },
	{ MODKEY,                       XK_i,      incnmaster,     {.i = +1 } },
	{ MODKEY,                       XK_d,      incnmaster,     {.i = -1 } },
	{ MODKEY,                       XK_h,      setmfact,       {.f = -0.05} },
	{ MODKEY,                       XK_l,      setmfact,       {.f = +0.05} },
	{ MODKEY,                       XK_Return, zoom,           {0} },
	{ MODKEY,                       XK_Tab,    view,           {0} },
	{ MODKEY|ShiftMask,             XK_c,      killclient,     {0} },
	{ MODKEY,                       XK_t,      setlayout,      {.v = &layouts[0]} },
	{ MODKEY,                       XK_f,      setlayout,      {.v = &layouts[1]} },
	{ MODKEY,                       XK_m,      setlayout,      {.v = &layouts[2]} },
	{ MODKEY,                       XK_space,  setlayout,      {0} },
	{ MODKEY|ShiftMask,             XK_space,  togglefloating, {0} },
	{ MODKEY,                       XK_0,      view,           {.ui = ~0 } },
	{ MODKEY|ShiftMask,             XK_0,      tag,            {.ui = ~0 } },
	{ MODKEY,                       XK_comma,  focusmon,       {.i = -1 } },
	{ MODKEY,                       XK_period, focusmon,       {.i = +1 } },
	{ MODKEY|ShiftMask,             XK_comma,  tagmon,         {.i = -1 } },
	{ MODKEY|ShiftMask,             XK_period, tagmon,         {.i = +1 } },
	TAGKEYS(                        XK_1,                      0)
	TAGKEYS(                        XK_2,                      1)
	TAGKEYS(                        XK_3,                      2)
	TAGKEYS(                        XK_4,                      3)
	TAGKEYS(                        XK_5,                      4)
	TAGKEYS(                        XK_6,                      5)
	TAGKEYS(                        XK_7,                      6)
	TAGKEYS(                        XK_8,                      7)
	TAGKEYS(                        XK_9,                      8)
	{ MODKEY|ShiftMask,             XK_q,      quit,           {0} },
};

/* button definitions */
/* click can be ClkTagBar, ClkLtSymbol, ClkStatusText, ClkWinTitle, ClkClientWin, or ClkRootWin */
static Button buttons[] = {
	/* click                event mask      button          function        argument */
	{ ClkLtSymbol,          0,              Button1,        setlayout,      {0} },
	{ ClkLtSymbol,          0,              Button3,        setlayout,      {.v = &layouts[2]} },
	{ ClkWinTitle,          0,              Button2,        zoom,           {0} },
	{ ClkStatusText,        0,              Button2,        spawn,          {.v = termcmd } },
	{ ClkClientWin,         MODKEY,         Button1,        movemouse,      {0} },
	{ ClkClientWin,         MODKEY,         Button2,        togglefloating, {0} },
	{ ClkClientWin,         MODKEY,         Button3,        resizemouse,    {0} },
	{ ClkTagBar,            0,              Button1,        view,           {0} },
	{ ClkTagBar,            0,              Button3,        toggleview,     {0} },
	{ ClkTagBar,            MODKEY,         Button1,        tag,            {0} },
	{ ClkTagBar,            MODKEY,         Button3,        toggletag,      {0} },
};
```

EDIT: Apoligies I'm patching the wrong file :/ I'm doing xresources patch instead of xrdb patch. Let's try with xrdb instead.

**Comment by mihirlad55** [comment] 2020-07-26 20:26
Wow this is an old issue. I'd recommend creating a new one as I don't think your issue is related to this one. I'd also suggest trying to re-apply the patch from scratch.

**Comment by Simbaclaws** [comment] 2020-07-26 20:36
Dear @mihirlad55 

I just found out that dwm-fullgaps and dwm-xrdb are conflicting with one another.
I'm not quite sure how to solve the conflict. I'll try finding a different gaps patch.

Switching to dwm-uselessgaps fixed the issue.
